CREATE TABLE IF NOT EXISTS masterdata.branch_midtier (
    branch_code varchar(4) NOT NULL,
    branch_name varchar(35) NOT NULL,
    branch_initial varchar(3) NOT NULL,
    dati2_code varchar(5) NOT NULL,
    region_code varchar(2) NOT NULL,
    branch_type varchar(15) NOT NULL,
    branch_coordinator varchar(35) NULL,
    kcu_code varchar(4) NULL,
    branch_longitude varchar(45) NOT NULL,
    branch_latitude varchar(45) NOT NULL,
    timezone varchar(4) NOT NULL,
    branch_address varchar(150) NOT NULL,
    branch_country varchar(35) NOT NULL,
    branch_city varchar(35) NULL,
    branch_province varchar(35) NOT NULL,
    zip_code varchar(5) NOT NULL,
    phone varchar(100) NOT NULL,
    fax varchar(40) NULL,
    branch_open_dt date NULL,
    effective_dt date NULL,
    branch_close_dt date NULL,
    strt_eff_dt date NULL,
    strt_end_dt date NULL,
    branch_sub_district varchar(100) NULL,
    emergency_close_strt_dt date NULL,
    emergency_close_end_dt date NULL,
    "version" int4 NULL DEFAULT 0,
    created_at timestamp NULL,
    created_by varchar(30) NULL,
    modified_at timestamp NULL,
    modified_by varchar(30) NULL,
    "path" _varchar NULL,
    soa_code varchar(30) NULL,
    last_update timestamp NULL,
    status varchar(30) NULL DEFAULT 'Active'::character varying,
    is_kp bool NULL DEFAULT false,
    CONSTRAINT branch_midtier_pk PRIMARY KEY (branch_code)
);