CREATE TABLE IF NOT EXISTS masterdata.building (
    branch_code varchar(4) NOT NULL,
    suffix      varchar(2) NOT NULL,
    rcc         varchar(3) NOT NULL,
    initial_code    varchar(20) NOT NULL UNIQUE,
    branch_name     varchar(255) NOT NULL,
    address         varchar(255) NOT NULL,
    under_management_property   BOOL DEFAULT NULL,
    car_parking_capacity            numeric(14),
    bike_parking_capacity           numeric(14),
    surface_certifivate_spacious    numeric(14,2),
    owner_status            varchar(255) NOT NULL,
    building_type_id        uuid DEFAULT uuid_generate_v4 (),
    building_alocation_id   uuid DEFAULT uuid_generate_v4 (),
    since_year              int4 DEFAULT NULL,
    surface_pbb_spacious    numeric(14,2),
    building_pbb_spacious   numeric(14,2),
    building_imb_spacious   numeric(14,2),
    total_emp_man           numeric(14),
    total_emp_woman         numeric(14),
    total_emp_man_os        numeric(14),
    total_emp_woman_os      numeric(14),
    activation_bfr          BOOL DEFAULT NULL,
    activation_bfr_desc     varchar(255) NOT NULL,
    activation              BOOL DEFAULT NULL,
    activation_desc         varchar(255) NOT NULL,
    "version" int4 NULL DEFAULT 0,
    created_at timestamp NULL,
    created_by varchar(30) NULL,
    modified_at timestamp NULL,
    modified_by varchar(30) NULL,
    CONSTRAINT building_pk PRIMARY KEY (branch_code,suffix)
);