-- `create Asset manual header` --
CREATE TABLE IF NOT EXISTS create_asset_manual_header(
    nomor_request           VARCHAR(255) NOT NULL,
    kode_organisasi         VARCHAR(50) DEFAULT NULL,
    jumlah_asset            INTEGER NULL DEFAULT 0,
    note                    TEXT DEFAULT NULL,
    status                  VARCHAR(50) DEFAULT NULL,
    requester_by            VARCHAR(255)  DEFAULT NULL,
    requester_dt            TIMESTAMP  DEFAULT NULL,
    processed_by            VARCHAR(255)  DEFAULT NULL,
    processed_dt            TIMESTAMP  DEFAULT NULL,
    is_processed            BOOL NULL DEFAULT 'false',
    search_string           TEXT NULL,
    version                 int4 NULL DEFAULT 0,
    created_at              TIMESTAMP NULL,
    created_by              VARCHAR(30) NULL,
    modified_at             TIMESTAMP NULL,
    modified_by             VARCHAR(30) NULL,
    CONSTRAINT create_asset_manual_header_pkey PRIMARY KEY (nomor_request)
);
-- `crate Asset manual DETAIL` --
CREATE TABLE IF NOT EXISTS create_asset_manual_detail(
    id                  BIGSERIAL NOT NULL,
    nomor_request       VARCHAR(50) NOT NULL,
    main_asset          VARCHAR(50) DEFAULT NULL,
    cost_center         VARCHAR(100) NOT NULL,
    tipe_at             VARCHAR(50) NOT NULL,
    asset_class         VARCHAR(10) NOT NULL,
    nomor_barcode       INTEGER NOT NULL,
    nama_barang         VARCHAR(255) NOT NULL,
    merk                VARCHAR(100) NOT NULL,
    tipe                VARCHAR(100) DEFAULT NULL,
    serial_number       VARCHAR(100) DEFAULT NULL,
    building_code       VARCHAR(20) NOT NULL,
    building_floor      VARCHAR(255) NOT NULL,
    pic                 VARCHAR(100) NOT NULL,
    tipe_software       VARCHAR(10) NOT NULL,
    status_aset             VARCHAR(10) NULL,
    nomor_po                VARCHAR(100) NULL,
    notes                   TEXT NULL,
    nomor_sertifikat        TEXT NULL,
    spesifikasi_standar     TEXT NULL,
    agreement_no            VARCHAR(100) NULL,
    kode_dati               VARCHAR(10) NULL,
    kode_kualitas           VARCHAR(10) NULL,
    harga_perolehan         NUMERIC(20,2) NOT NULL,
    slid_tampungan          VARCHAR(100) DEFAULT NULL,
    coa_tampungan           VARCHAR(10) DEFAULT NULL,
    sub_coa_tampungan       VARCHAR(10) DEFAULT NULL,
    cost_center_tampungan   VARCHAR(100) DEFAULT NULL,
    product_code_tampungan  VARCHAR(10) DEFAULT NULL,
    search_string           TEXT NULL,
    version                 int4 NULL DEFAULT 0,
    created_at              TIMESTAMP NULL,
    created_by              VARCHAR(30) NULL,
    modified_at             TIMESTAMP NULL,
    modified_by             VARCHAR(30) NULL,
    CONSTRAINT create_asset_manual_detail_pkey PRIMARY KEY (id),
    CONSTRAINT fk_nomor_request FOREIGN KEY (nomor_request) REFERENCES create_asset_manual_header (nomor_request),
    CONSTRAINT fk_cost_center FOREIGN KEY (cost_center) REFERENCES masterdata.cost_center (cost_center_id),
    CONSTRAINT fk_tipe_at FOREIGN KEY (tipe_at) REFERENCES tipe_at (kode),
    CONSTRAINT fk_status_aset FOREIGN KEY (status_aset) REFERENCES status_asset (kode),
    CONSTRAINT fk_asset_class FOREIGN KEY (asset_class) REFERENCES masterdata.asset_class (asset_class),
    CONSTRAINT fk_building_code FOREIGN KEY (building_code) REFERENCES masterdata.building (initial_code),
    CONSTRAINT fk_building_floor FOREIGN KEY (building_floor) REFERENCES masterdata.building_detail_spacious (building_detail_spacious_id),
    CONSTRAINT fk_tipe_software FOREIGN KEY (tipe_software) REFERENCES tipe_software (kode),
    CONSTRAINT fk_coa_tampungan FOREIGN KEY (coa_tampungan) REFERENCES masterdata.coa (coa_code),
    CONSTRAINT fk_sub_coa_tampungan FOREIGN KEY (coa_tampungan, sub_coa_tampungan) REFERENCES masterdata.sub_coa (coa_code, sub_coa_code),
    CONSTRAINT fk_product_code_tampungan FOREIGN KEY (product_code_tampungan) REFERENCES masterdata.kode_produk (product_code),
    CONSTRAINT fk_cost_center_tampungan FOREIGN KEY (cost_center_tampungan) REFERENCES masterdata.cost_center (cost_center_id),
    CONSTRAINT fk_kode_dati FOREIGN KEY (kode_dati) REFERENCES kode_dati (kode),
    CONSTRAINT fk_kode_kualitas FOREIGN KEY (kode_kualitas) REFERENCES kode_kualitas (kode)
);

-- `crate Asset` --
CREATE TABLE IF NOT EXISTS asset(
    nomor_aset_tetap        VARCHAR(50) NOT NULL,
    sub_nomor_aset_tetap    VARCHAR(50) NOT NULL,
    aset_created_on         DATE DEFAULT NULL,
    transaction_type        VARCHAR(100) NOT NULL,
    transaction_detail_id   BIGSERIAL NOT NULL,
    cost_center             VARCHAR(100) NOT NULL,
    tipe_at                 VARCHAR(50) NOT NULL,
    asset_class             VARCHAR(10) NOT NULL,
    nomor_barcode           INTEGER NOT NULL,
    nama_barang             VARCHAR(255) NOT NULL,
    merk                    VARCHAR(100) NOT NULL,
    tipe                    VARCHAR(100) NULL,
    serial_number           VARCHAR(100) NULL,
    building_code           VARCHAR(20) NOT NULL,
    building_floor          VARCHAR(255) NOT NULL,
    pic                     VARCHAR(100) NULL,
    tipe_software           VARCHAR(10) NULL,
    status_aset             VARCHAR(10) NULL,
    nomor_po                VARCHAR(100) NULL,
    notes                   TEXT NULL,
    nomor_sertifikat        TEXT NULL,
    spesifikasi_standar     TEXT NULL,
    agreement_no            VARCHAR(100) NULL,
    kode_dati               VARCHAR(10) NULL,
    kode_kualitas           VARCHAR(10) NULL,
    flag                    VARCHAR(100) NULL,
    search_string           TEXT NULL,
    version                 int4 NULL DEFAULT 0,
    created_at              TIMESTAMP NULL,
    created_by              VARCHAR(30) NULL,
    modified_at             TIMESTAMP NULL,
    modified_by             VARCHAR(30) NULL,
    CONSTRAINT asset_pkey PRIMARY KEY (nomor_aset_tetap,sub_nomor_aset_tetap),
    CONSTRAINT fk_transaction_detail_id FOREIGN KEY (transaction_detail_id) REFERENCES create_asset_manual_detail (id),
    CONSTRAINT fk_cost_center FOREIGN KEY (cost_center) REFERENCES masterdata.cost_center (cost_center_id),
    CONSTRAINT fk_tipe_at FOREIGN KEY (tipe_at) REFERENCES tipe_at (kode),
    CONSTRAINT fk_status_aset FOREIGN KEY (status_aset) REFERENCES status_asset (kode),
    CONSTRAINT fk_asset_class FOREIGN KEY (asset_class) REFERENCES masterdata.asset_class (asset_class),
    CONSTRAINT fk_building_code FOREIGN KEY (building_code) REFERENCES masterdata.building (initial_code),
    CONSTRAINT fk_building_floor FOREIGN KEY (building_floor) REFERENCES masterdata.building_detail_spacious (building_detail_spacious_id),
    CONSTRAINT fk_tipe_software FOREIGN KEY (tipe_software) REFERENCES tipe_software (kode),
    CONSTRAINT fk_kode_dati FOREIGN KEY (kode_dati) REFERENCES kode_dati (kode),
    CONSTRAINT fk_kode_kualitas FOREIGN KEY (kode_kualitas) REFERENCES kode_kualitas (kode)
);

-- `Attachment` --
CREATE TABLE IF NOT EXISTS attachment(
    document_no             VARCHAR(255) NOT NULL,
    document_type           VARCHAR(255) NOT NULL,
    transaction_type        VARCHAR(255) NOT NULL,
    transaction_id          VARCHAR(255) NOT NULL,
    file_url                VARCHAR(255) DEFAULT NULL,
    file_name               VARCHAR(255) DEFAULT NULL,
    file_type               VARCHAR(255) DEFAULT NULL,
    description             TEXT DEFAULT NULL,
    search_string           TEXT NULL,
    version                 int4 NULL DEFAULT 0,
    created_at              TIMESTAMP NULL,
    created_by              VARCHAR(30) NULL,
    modified_at             TIMESTAMP NULL,
    modified_by             VARCHAR(30) NULL,
    CONSTRAINT attachment_pkey PRIMARY KEY (document_no),
    CONSTRAINT fk_transaction_id FOREIGN KEY (transaction_id) REFERENCES create_asset_manual_header (nomor_request)
);

CREATE TABLE IF NOT EXISTS asset_financial(
    nomor_aset_tetap        VARCHAR(50) NOT NULL,
    sub_nomor_aset_tetap    VARCHAR(50) NOT NULL,
    tanggal_akuisisi        DATE NULL,
    harga_perolehan         NUMERIC(20,2) NOT NULL,
    nilai_buku              NUMERIC(20,2) NULL DEFAULT 0,
    nilai_buku_awal         NUMERIC(20,2) NULL DEFAULT 0,
    akumulasi_sd_awal_tahun         INTEGER NOT NULL,
    akumulasi_sd_bulan_transaksi    INTEGER NOT NULL,
    last_updated            TIMESTAMP NULL,
    CONSTRAINT asset_financial_pkey PRIMARY KEY (nomor_aset_tetap,sub_nomor_aset_tetap)
);

-- AUDIT TABLE --
-- Asset AUD --
CREATE TABLE IF NOT EXISTS create_asset_manual_header_aud(
    revision_id             int4 NOT NULL,
    revision_type           int4 NOT NULL,
    nomor_request           VARCHAR(255) NOT NULL,
    kode_organisasi         VARCHAR(50) DEFAULT NULL,
    jumlah_asset            INTEGER NULL DEFAULT 0,
    note                    TEXT DEFAULT NULL,
    status                  VARCHAR(50) DEFAULT NULL,
    requester_by            VARCHAR(255)  DEFAULT NULL,
    requester_dt            TIMESTAMP  DEFAULT NULL,
    processed_by            VARCHAR(255)  DEFAULT NULL,
    processed_dt            TIMESTAMP  DEFAULT NULL,
    is_processed            BOOL NULL DEFAULT 'false',
    search_string           TEXT NULL,
    version                 int4 NULL DEFAULT 0,
    created_at              TIMESTAMP NULL,
    created_by              VARCHAR(30) NULL,
    modified_at             TIMESTAMP NULL,
    modified_by             VARCHAR(30) NULL,
    CONSTRAINT create_asset_manual_header_aud_pk PRIMARY KEY (revision_id, revision_type, nomor_request),
    CONSTRAINT fk_create_asset_manual_header_aud FOREIGN KEY (revision_id) REFERENCES revision_info (revision_id)
);

-- Asset DETAIL AUD --
CREATE TABLE IF NOT EXISTS create_asset_manual_detail_aud(
    revision_id             int4 NOT NULL,
    revision_type           int4 NOT NULL,
    id                  BIGSERIAL NOT NULL,
    nomor_request       VARCHAR(50) NOT NULL,
    main_asset          VARCHAR(50) DEFAULT NULL,
    cost_center         VARCHAR(100) NOT NULL,
    tipe_at             VARCHAR(50) NOT NULL,
    asset_class         VARCHAR(10) NOT NULL,
    nomor_barcode       INTEGER NOT NULL,
    nama_barang         VARCHAR(255) NOT NULL,
    merk                VARCHAR(100) NOT NULL,
    tipe                VARCHAR(100) DEFAULT NULL,
    serial_number       VARCHAR(100) DEFAULT NULL,
    building_code       VARCHAR(20) NOT NULL,
    building_floor      VARCHAR(255) NOT NULL,
    pic                 VARCHAR(100) NOT NULL,
    tipe_software       VARCHAR(10) NOT NULL,
    status_aset             VARCHAR(10) NULL,
    nomor_po                VARCHAR(100) NULL,
    notes                   TEXT NULL,
    nomor_sertifikat        TEXT NULL,
    spesifikasi_standar     TEXT NULL,
    agreement_no            VARCHAR(100) NULL,
    kode_dati               VARCHAR(10) NULL,
    kode_kualitas           VARCHAR(10) NULL,
    harga_perolehan         NUMERIC(20,2) NOT NULL,
    slid_tampungan          VARCHAR(100) DEFAULT NULL,
    coa_tampungan           VARCHAR(10) DEFAULT NULL,
    sub_coa_tampungan       VARCHAR(10) DEFAULT NULL,
    cost_center_tampungan   VARCHAR(50) DEFAULT NULL,
    product_code_tampungan  VARCHAR(10) DEFAULT NULL,
    search_string           TEXT NULL,
    version                 int4 NULL DEFAULT 0,
    created_at              TIMESTAMP NULL,
    created_by              VARCHAR(30) NULL,
    modified_at             TIMESTAMP NULL,
    modified_by             VARCHAR(30) NULL,
    CONSTRAINT create_asset_manual_detail_aud_pk PRIMARY KEY (revision_id, revision_type, id, nomor_request),
    CONSTRAINT fk_create_asset_manual_detail_aud FOREIGN KEY (revision_id) REFERENCES revision_info (revision_id)
);

-- Asset  AUD --
CREATE TABLE IF NOT EXISTS asset_aud(
    revision_id             int4 NOT NULL,
    revision_type           int4 NOT NULL,
    nomor_aset_tetap        VARCHAR(50) NOT NULL,
    sub_nomor_aset_tetap    VARCHAR(50) NOT NULL,
    aset_created_on         DATE DEFAULT NULL,
    transaction_type        VARCHAR(100) NOT NULL,
    transaction_detail_id   BIGSERIAL NOT NULL,
    cost_center             VARCHAR(100) NOT NULL,
    tipe_at                 VARCHAR(50) NOT NULL,
    asset_class             VARCHAR(10) NOT NULL,
    nomor_barcode           INTEGER NOT NULL,
    nama_barang             VARCHAR(255) NOT NULL,
    merk                    VARCHAR(100) NOT NULL,
    tipe                    VARCHAR(100) NULL,
    serial_number           VARCHAR(100) NULL,
    building_code           VARCHAR(20) NOT NULL,
    building_floor          VARCHAR(255) NOT NULL,
    pic                     VARCHAR(100) NULL,
    tipe_software           VARCHAR(10) NULL,
    status_aset             INTEGER NOT NULL,
    nomor_po                VARCHAR(100) NULL,
    notes                   TEXT NULL,
    nomor_sertifikat        TEXT NULL,
    spesifikasi_standar     TEXT NULL,
    agreement_no            VARCHAR(100) NULL,
    kode_dati               VARCHAR(100) NULL,
    flag                    VARCHAR(100) NULL,
    kode_kualitas           VARCHAR(100) NULL,
    search_string           TEXT NULL,
    version                 int4 NULL DEFAULT 0,
    created_at              TIMESTAMP NULL,
    created_by              VARCHAR(30) NULL,
    modified_at             TIMESTAMP NULL,
    modified_by             VARCHAR(30) NULL,
    CONSTRAINT asset_aud_pk PRIMARY KEY (revision_id, revision_type, nomor_aset_tetap,sub_nomor_aset_tetap),
    CONSTRAINT fk_asset_aud FOREIGN KEY (revision_id) REFERENCES revision_info (revision_id)
);

-- Asset Attachment AUD --
CREATE TABLE IF NOT EXISTS attachment_aud(
    revision_id             int4 NOT NULL,
    revision_type           int4 NOT NULL,
    document_no             VARCHAR(255) NOT NULL,
    document_type           VARCHAR(255) NOT NULL,
    transaction_type        VARCHAR(255) NOT NULL,
    transaction_id          VARCHAR(255) NOT NULL,
    file_url                VARCHAR(255) DEFAULT NULL,
    file_name               VARCHAR(255) DEFAULT NULL,
    file_type               VARCHAR(255) DEFAULT NULL,
    description             TEXT DEFAULT NULL,
    search_string           TEXT NULL,
    version                 int4 NULL DEFAULT 0,
    created_at              TIMESTAMP NULL,
    created_by              VARCHAR(30) NULL,
    modified_at             TIMESTAMP NULL,
    modified_by             VARCHAR(30) NULL,
    CONSTRAINT attachment_aud_pk PRIMARY KEY (revision_id, revision_type, document_no),
    CONSTRAINT fk_attachment_aud FOREIGN KEY (revision_id) REFERENCES revision_info (revision_id)
);

-- Asset financial AUD --
CREATE TABLE IF NOT EXISTS asset_financial_aud(
    revision_id             int4 NOT NULL,
    revision_type           int4 NOT NULL,
    nomor_aset_tetap        VARCHAR(50) NOT NULL,
    sub_nomor_aset_tetap    VARCHAR(50) NOT NULL,
    tanggal_akuisisi        DATE NULL,
    harga_perolehan         NUMERIC(20,2) NOT NULL,
    nilai_buku              NUMERIC(20,2) NULL DEFAULT 0,
    nilai_buku_awal         NUMERIC(20,2) NULL DEFAULT 0,
    akumulasi_sd_awal_tahun         INTEGER NOT NULL,
    akumulasi_sd_bulan_transaksi    INTEGER NOT NULL,
    last_updated            TIMESTAMP NULL,
    version                 int4 NULL DEFAULT 0,
    created_at              TIMESTAMP NULL,
    created_by              VARCHAR(30) NULL,
    modified_at             TIMESTAMP NULL,
    modified_by             VARCHAR(30) NULL,
    CONSTRAINT asset_financial_aud_pk PRIMARY KEY (revision_id, revision_type, nomor_aset_tetap, sub_nomor_aset_tetap),
    CONSTRAINT fk_asset_financial_aud FOREIGN KEY (revision_id) REFERENCES revision_info (revision_id)
);